#!/usr/bin/env python3
"""
build.py - build the browser version of the AK Base Kit demo (WebAssembly).

  python port/web/build.py                    # -> <repo>/docs/play/
  python port/web/build.py --out some/folder
  python port/web/build.py --emcc D:/emsdk/upstream/emscripten/emcc.bat

Needs the Emscripten SDK (https://emscripten.org): emcc on the PATH (run
emsdk_env first), or --emcc. The result is a handful of static files -
index.html (one kit), pong.html (two kits on one RS485 line), kit-ui.js,
page.css and ak-kit.js (the firmware; the WebAssembly is inside the .js) -
that also work when opened straight from disk.
"""

import argparse
import glob
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))               # ak-mcu-base
REPO = os.path.dirname(ROOT)

SOURCES = [
    "kernel/src/*.c", "common/*.c",
    "services/fw/fw_image.c", "services/fw/fw_update.c", "services/fw/fw_proto.c", "services/fw/boot_ctrl.c",
    "services/sys/*.c", "services/modbus/*.c", "third_party/nanomodbus/nanomodbus.c",
    "app/*.c", "demo/*.c",
    "port/host/port_host.c", "port/web/web_main.c",
]
INCLUDES = ["kernel/inc", "common", "hal", "services/fw", "services/sys", "services/modbus",
            "third_party/nanomodbus", "boot", "app", "demo", "port/host"]
# APP_CRASH_TEST=0: "crash test hang" and "test fault" would freeze or kill the page
DEFINES = ["AK_SIM", "APP_KIT_DEMO", "APP_MODBUS_SLAVE", "NMBS_CLIENT_DISABLED", "NMBS_STRERROR_DISABLED",
           "APP_CRASH_TEST=0"]


def clip_header(src, dst):
    data = open(src, "rb").read()
    with open(dst, "w") as f:
        f.write("/* generated by port/web/build.py from %s */\n" % os.path.basename(src))
        f.write("static const unsigned char clip_data[%d] = {\n" % len(data))
        for i in range(0, len(data), 20):
            f.write("\t" + ",".join("%d" % b for b in data[i:i + 20]) + ",\n")
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=os.path.join(REPO, "docs", "play"))
    ap.add_argument("--emcc", default=None, help="path of emcc (default: from the PATH)")
    ap.add_argument("--work", default=os.path.join(ROOT, "build", "web"), help="folder for generated files")
    a = ap.parse_args()

    emcc = a.emcc or shutil.which("emcc")
    if not emcc:
        raise SystemExit("emcc not found: activate the Emscripten SDK (emsdk_env) or pass --emcc")
    os.makedirs(a.out, exist_ok=True)
    os.makedirs(a.work, exist_ok=True)
    clip_header(os.path.join(HERE, "clip.akv"), os.path.join(a.work, "clip_data.h"))

    files = []
    for pattern in SOURCES:
        found = sorted(glob.glob(os.path.join(ROOT, pattern)))
        if not found:
            raise SystemExit("no source matches " + pattern)
        files += found

    cmd = [emcc, "-O2", "-std=gnu99", "-Wall", "-Wno-unused-parameter"]
    cmd += ["-D" + d for d in DEFINES]
    cmd += ["-I" + os.path.join(ROOT, i) for i in INCLUDES] + ["-I" + a.work]
    cmd += files
    cmd += [
        "-sSINGLE_FILE=1",                  # the .wasm goes into the .js: works from file://
        "-sMODULARIZE=1", "-sEXPORT_NAME=AkKit",
        "-sENVIRONMENT=web",
        "-sEXPORTED_RUNTIME_METHODS=HEAPU8",
        "-sSUPPORT_LONGJMP=emscripten",     # FATAL and reset leave the kernel with longjmp
        "-sALLOW_MEMORY_GROWTH=0",
        "-o", os.path.join(a.out, "ak-kit.js"),
    ]
    print("emcc: %d source files" % len(files))
    subprocess.check_call(cmd)
    pages = ("index.html", "pong.html", "kit-ui.js", "page.css", "social.png")
    for name in pages:
        shutil.copyfile(os.path.join(HERE, name), os.path.join(a.out, name))
    for name in pages + ("ak-kit.js",):
        print("%-11s %7d bytes" % (name, os.path.getsize(os.path.join(a.out, name))))


if __name__ == "__main__":
    main()
